build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"credsStore\":\"ecr-login\"}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/tools/rufes-evaluation/docker"
      --dockerfile "${CI_PROJECT_DIR}/tools/rufes-evaluation/docker/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
      --destination "${ECR_IMAGE_REF}:${CI_COMMIT_SHORT_SHA}"
      --destination "${ECR_IMAGE_REF}:${CI_COMMIT_BRANCH}"
  rules:
    - if: $CI_COMMIT_BRANCH
