build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/tools/rufes-evaluation/docker"
      --dockerfile "${CI_PROJECT_DIR}/tools/rufes-evaluation/docker/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
  # rules:
  #   - if: $CI_COMMIT_TAG